#!/usr/bin/env bash
#
# Run all dotfiles installers.
#

# Exit if any subcommand or pipeline returns a non-zero status.
set -e

# Change permissions first
chmod -R +x *

## Go up one level.
#cd "$(dirname "$0")/.."

printf "\\r› Installing packages and applications.\\n\\n"
#brew bundle --file homebrew/Brewfile > /dev/null
brew bundle --file homebrew/Brewfile

# Find the installers and run them iteratively.
find . -name install.sh | while read -r installer ; do sh -c "${installer}" ; done

#
# Standard dotbot pre-configuration:
#

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# Linking dotfiles:

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile --plugin-dir dotbot-pip -c "${CONFIG}" "${@}"
