#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/usr/local/bin:$PATH"

export PATH=/usr/local/bin:$PATH

export PATH="$HOME/.poetry/bin:$PATH"

alias python='python3
