# Keep 10000000000 lines of history within the shell
HISTSIZE=10000000000
SAVEHIST=10000000000
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"

# Path to your oh-my-zsh installation.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="false"

# PLUGINS
plugins=(git gitfast docker docker-compose osx last-working-dir common-aliases zsh-autosuggestions zsh-syntax-highlighting history-substring-search pip bundler poetry python brew)

export PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
source "$HOME/.shell_env"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)

export PATH="$HOME/.poetry/bin:$PATH"

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

